"""
Django settings for cetaf_survey_api project.
Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG")

ALLOWED_HOSTS = [os.getenv("ALLOWED_HOST"), "127.0.0.1", "localhost"]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'cetaf_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cetaf_survey_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cetaf_survey_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv("POSTGRES_DB"),
        'USER': os.getenv("POSTGRES_USER"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
        'HOST': os.getenv("POSTGRES_HOST"),
        'PORT': os.getenv("POSTGRES_PORT"),
    }
}

ES_URL = os.getenv("ES_URL")
ES_INDEX_INSTITUTIONS=os.getenv("ES_INDEX_INSTITUTIONS")
ES_INDEX_COLLECTIONS=os.getenv("ES_INDEX_COLLECTIONS")
ES_INDEX_THESAURUS_DISCIPLINES=os.getenv("ES_INDEX_THESAURUS_DISCIPLINES")

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': True,
#     'formatters': {
#         'verbose': {
#             'format': '%(asctime)s %(levelname)s [%(name)s:%(lineno)s] %(module)s %(process)d %(thread)d %(message)s'
#         }
#     },
#     'handlers': {
#         'gunicorn': {
#             'level': 'DEBUG',
#             'class': 'logging.handlers.RotatingFileHandler',
#             'formatter': 'verbose',
#             'filename': '/opt/cetaf_passport_api/logs/gunicorn.errors',
#             'maxBytes': 1024 * 1024 * 100,  # 100 mb
#         }
#     },
#     'loggers': {
#         'gunicorn.errors': {
#             'level': 'DEBUG',
#             'handlers': ['gunicorn'],
#             'propagate': True,
#         },
#     }
# }
####

CETAF_DATA_ADDRESS={
        "institutions": os.getenv("CETAF_DATA_ADDRESS_institutions"),
        "collection_overview": os.getenv("CETAF_DATA_ADDRESS_collection_overview"),      
        "collection_root_folder":os.getenv("CETAF_DATA_ADDRESS_collection_root_folder")
    }

DEFAULT_QUERY_SIZE=10   

ORCID_ROOT_URL=os.getenv("ORCID_ROOT_URL")
ORCID_CLIENT_ID=os.getenv("ORCID_CLIENT_ID")
ORCID_CLIENT_SECRET=os.getenv("ORCID_CLIENT_SECRET")

GOOGLE_AUTH_FILE=os.getenv("GOOGLE_AUTH_FILE")
GOOGLE_CLOUD_REFRESH_TOKEN=os.getenv("GOOGLE_CLOUD_REFRESH_TOKEN")
GOOGLE_CLOUD_CLIENT_ID=os.getenv("GOOGLE_CLOUD_CLIENT_ID")
GOOGLE_CLOUD_SECRET=os.getenv("GOOGLE_CLOUD_SECRET")
GOOGLE_CLOUD_REDIRECT_URI=os.getenv("GOOGLE_CLOUD_REDIRECT_URI")
GOOGLE_CLOUD_REFRESH_URL=os.getenv("GOOGLE_CLOUD_REFRESH_URL")
GOOGLE_SHEET_URL=os.getenv("GOOGLE_SHEET_URL")

MAPPING_G_SHEET={
    "institutions": {
        "timestamp":0,
        "timestamp_format":"%d/%m/%Y %H:%M:%S",
        "timestamp_default":"01/01/0001 00:00:00",
        "fields":
        {
            8: "name_institution_en",
            9: "name_institution_en_alternate",
            12: "original_name",
            "address":
            {
                21 : "street",
                22: "city",
                23 :"province",
                24: "postcode" ,
                25: "country"
            }
            ,
            "contact":
            {
                27: "phone",
                28: "mail"
            },
            "social_network":
            {
                30: "X",
                31: "Facebook",
                32: "Instagram",
                33: "LinkedIn",
                34: "YouTube",
            },
            "institution_data":
            {
                10: "logo",
                29: "website",
            },
            "direction":
             {
                41: "title",
                43: "first_name",
                44: "last_name",
                45: "phone",
                46: "mail",
                47: "orcid"
             },
             "organisation":
             {
                48: "chart_description",
                49: "chart_url",
                50: "chart_file",
                51: "governing_and_executive_bodies",
                52: "year_data"
             },
             58: "cetaf_membership",
             "cetaf_representative":
             {
                59: "title",
                61: "first_name",
                62: "last_name",
                64: "phone",
                63: "mail",
                65: "orcid",
                66: "role_in_institution"
             },
             "cetaf_executive_1":
             {
                69: "title",
                71: "first_name",
                72: "last_name",
                73: "phone",
                74: "mail",
                75: "orcid",
                76: "role_in_institution"
             },
             "cetaf_executive_2":
             {
                79: "title",
                81: "first_name",
                82: "last_name",
                83: "phone",
                84: "mail",
                85: "orcid",
                86: "role_in_institution"
             }
        },
        "array_fields":
        {
            3: {"name": "membership", "delimiter":"," }
        },       
        "identifiers_api":
        {
            35: "ror"
        },
        "main_identifier_db": {
            "fields" :
            {
                8: "name_institution_en",
                9: "name_institution_en_alternate",
                12: "original_name",
             },
             "null_value":"Other"
        },
        "other_identifiers":
        {
            35: "ror",
            36: "grid",
            37: "index_herbarium",
            38: "wikidata",
            39: "isni",
            40: "grscicoll",
        }
        ,
        "apis":
        {
            #keep this order for grscicoll
            "ror":35,
            "grscicoll_institutions":40,
            "grscicoll_collections_from_institutions" : None
        }
    }
}

#alternate mapmping identifier in column
MAPPING_G_SHEET_OVERVIEW={
    "cetaf_collection_overview":
    {
        "institution_id_fields":
        {
            "institution_name":4,
            "alternate_institution_name":5
        },
        "appended_excel":
        {
            "collection_size": { "col":25, "sheet": "Collection overview"}
        }
    }
}

#keep this order for grscicoll
APIS_SHEET={
    "ror": {
            "endpoint":"https://api.ror.org/v2/organizations/",
            "mapping":
                {
                }
    },
    "grscicoll_institutions": {
            "endpoint":"https://api.gbif.org/v1/grscicoll/institution/latimerCore?code=",
            "mapping":
                {
                }
    },
    "grscicoll_collections_from_institutions": {
            "endpoint":"https://api.gbif.org/v1/grscicoll/collection/latimerCore?institutionKey=",
            "mapping":
                {
                }
    }   
}

COLLECTION_ACRONYMS_MAPPING={
    'AFP':'Botany',
    'AFP-NS':'Botany unspecified',
    'AFP-ALG':'Botany - Algae',
    'AFP-FUN':'Botany - Macrofungi, Lichens & Myxomycetes',
    'AFP-BRY':'Botany - Bryophytes',
    'AFP-PTE':'Botany - Pteridophytes',
    'AFP-SEE':'Botany - Seed plants',
    'AFP-PGR':'Botany - Plants genetic Resources',
    'AFP-OTH':'Botany - Other Botany objects',
    'INV':'Invertebrates',
    'INV-NS':'Invertebrates unspecified',
    'INV-INS':'Invertebrates - Insects',
    'INV-ARA':'Invertebrates - Arachnids',
    'INV-CRU':'Invertebrates - Crustaceans & myriapods',
    'INV-MOL':'Invertebrates - Mollusca (bivalves, gastropods, cephalopods)',
    'INV-POR':'Invertebrates - Porifera (sponges)',
    'INV-CNI':'Invertebrates - Cnidaria (jellyfish, coral, anemones)',
    'INV-ECH':'Invertebrates - Echinodermata (starfish, sea urchins, sea cucumbers)',
    'INV-IGR':'Invertebrates - Invertebrates Genetic Resources',
    'INV-OTH':'Invertebrates - Other Invertebrates zoology objects',
    'VER':'Vertebrates',
    'VER-NS':'Vertebrates unspecified',
    'VER-FIS':'Vertebrates - Fishes',
    'VER-AMP':'Vertebrates - Amphibians',
    'VER-REP':'Vertebrates - Reptiles',
    'VER-BIR':'Vertebrates - Birds',
    'VER-MAM':'Vertebrates - Mammals',
    'VER-VGR':'Vertebrates - Genetic resources',
    'VER-OTH':'Vertebrates - Others',
    'ANT':'Anthropology',
    'ANT-NS':'Anthropology unspecified',
    'ANT-BIO':'Anthropology - Biological Anthropology',
    'ANT-ARC':'Anthropology - Archeology',
    'ANT-AGR':'Anthropology - Anthropology Genetic Resources',
    'ANT-OTH':'Anthropology - Anthropology Other',
    'PAL':'Paleontology',
    'PAL-NS':'Palaeontology unspecified',
    'PAL-AFP':'Paleontology - Fossil Plants & Fungi',
    'PAL-INV':'Paleontology - Fossil Invertebrates',
    'PAL-VER':'Paleontology - Fossil Vertebrates',
    'PAL-OTH':'Paleontology - Palaeontology Others',
    'GEO':'Geology',
    'GEO-NS':'Geology unspecified',
    'GEO-MIN':'Geology - Minerals and Gems',
    'GEO-PET':'Geology - Petrology',
    'GEO-SED':'Geology - Sediments',
    'GEO-SOI':'Geology - Soils',
    'GEO-ICE':'Geology - Water - Ice',
    'GEO-LGS':'Geology - Liquid or gaseous',
    'GEO-MSS':'Geology - Mixed Geology',
    'GEO-OTH':'Geology - Geology Other',
    'AST':'Astrogeology',
    'AST-NS':'Astrogeology unspecified',
    'AST-SPA':'Astrogeology - Sample returns',
    'AST-MET':'Astrogeology - Terrestrial finds/falls (e.g. meteorites)',
    'AST-TEC':'Astrogeology - Terrestrial impacta (e.g. tectites)',
    'AST-IMP':'Astrogeology - Terrestrial impacta (e.g. tectites)',
    'AST-OTH':'Astrogeology - Astrogeology Others',
    'ECO':'Ecology',
    'ECO-NS':'Ecology Unspecified',
    'ECO-DNA':'Ecology  - Ecology e-DNA',
    'ECO-OTH':'Ecology  - Ecology Other items',
    'MIC':'Microbiology',
    'MIC-NS':'Microbiology unspecified',
    'MIC-PHA':'Microbiology-Phages',
    'MIC-BAC':'Microbiology-Bacteria & Archea',
    'MIC-PLA':'Microbiology-Plasmids',
    'MIC-PRO':'Microbiology-Protozoa',
    'MIC-EUK':'Microbiology-Eukaroriotic microorganisms',
    'MIC-VIR':'Microbiology-Virus',
    'MIC-YEA':'Microbiology-Microfungi',
    'MIC-ALG':'Microbiology-Algae',
    'MIC-OTH':'Microbiology-Other microorganisms',
    'HER':'Heritage',
    'HER-NS':'Heritage Unspecified',
    'HER-DOC':'Heritage - Documentation',
    'HER-LIB':'Heritage - Library',
    'HER-PIC':'Heritage - Pictures',
    'HER-SOU':'Heritage - Sounds',
    'HER-MOD':'Heritage - Models',
    'HER-OTH':'Heritage - Heritage Other',
    'DAT':'Data',
    'DAT-NS':'Data Unspecified',
    'DAT-MEA':'Data - Measurements',
    'DAT-OBS':'Data - Observations',
    'DAT-DIB':'Data - Digital Born',
    'DAT-DIG':'Data - Digitisation',
    'DAT-MET':'Data - Metadata',
}

INTERNAL_COLLECTION_LINK="https://naturalheritage.africamuseum.be/cetaf_survey_api/collections/?operation=get_by_id&protocol=cetaf&values="
